### ISSUE TITLE
Errors with default instructions (Ubuntu 20.04, Gradle 6.4.1, OpenJDK 11)

### ISSUE THREAD

**Issue by ColinChargy** [leek-wars/leek-wars-generator#1]
Hi,
I can speak French, if you wish.
I have checkouted this code and ran `gradle jar` without errors. However `java -jar generator.jar --compile test/ai/basic.leek` answered:
```
java.lang.NullPointerException
	at com.leekwars.generator.attack.weapons.Weapon.<init>(Weapon.java:31)
	at com.leekwars.generator.Generator.loadWeapons(Generator.java:199)
	at com.leekwars.generator.Generator.<init>(Generator.java:71)
	at com.leekwars.Main.main(Main.java:53)
Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error, pos 1
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1085)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1011)
	at com.alibaba.fastjson.JSON.parse(JSON.java:94)
	at com.alibaba.fastjson.JSON.parse(JSON.java:85)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:156)
	at com.leekwars.generator.scenario.Scenario.fromFile(Scenario.java:39)
	at com.leekwars.Main.main(Main.java:59)
```
It seems that the first error is due to the absence of "passive_effects" array in passive_effects.
The second one seems to be because basic.leek is not a JSON file, shouldn't it be `java -jar generator.jar --compile test/scenario/scenario1.json` instead ?
If a do that, I get these errors :
```
java.lang.NullPointerException
	at com.leekwars.generator.attack.weapons.Weapon.<init>(Weapon.java:31)
	at com.leekwars.generator.Generator.loadWeapons(Generator.java:199)
	at com.leekwars.generator.Generator.<init>(Generator.java:71)
	at com.leekwars.Main.main(Main.java:53)
Exception in thread "main" java.lang.NullPointerException
	at com.leekwars.generator.Generator.runScenario(Generator.java:138)
	at com.leekwars.Main.main(Main.java:64)
```
How should I solve thoses ?

By the way, I'm trying to simulate fight locally to be able to train Machine-Learning-based AIs for my leeks. Should I run it directly with https://github.com/leek-wars/leek-wars-generator and LeekScript V2 ? Are all the features currently in LeekWars all enabled with this new version of generator and LeekScript ?

Thanks anyway for developing LeekWars,
Regards,
Colin Chargy

**Comment by BaptisteHudyma** [comment]
Hello!
I happen to get the same problem. Solved it [here](https://github.com/leek-wars/leek-wars-generator-v1/pull/2) .
Still getting red flags from the tests but at least it's running...
Hope you get it running 

B Hudyma

Edit:
BTW, the correct commands are:
`java -jar generator.jar --analyze test/ai/your_ai.leek`
and
`java -jar generator.jar --compile test/scenario/your_scenario.json`

**Comment by 5pilow** [comment]
Hello, this is now fixed!
